[package]
name = "vpzip-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Graphical interface for VPZip — a multilingual archiver for Valve Source engine formats."

[[bin]]
name = "vpzip-gui"
path = "src/main.rs"

[dependencies]
vpzip-core = { path = "../vpzip-core" }
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
rfd.workspace = true
image.workspace = true
rust-i18n.workspace = true
serde = { workspace = true }
serde_json.workspace = true

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
