[package]
name = "vpzip-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for VPZip."

[[bin]]
name = "vpzip"
path = "src/main.rs"

[dependencies]
vpzip-core = { path = "../vpzip-core" }
anyhow.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true
indicatif.workspace = true

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dev-dependencies]
vpzip-core = { path = "../vpzip-core" }
